[package]
name    = "rust_version"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap       = { version = "4.0.29", features = ["derive"] }
derivative = "2.2.0"
num_enum   = "0.5.7"
shrinkwraprs = "0.3.0"
paste = "1.0.9"