# This workflow will build the rust interpreter of lox

name: rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust_version
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: make test